name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]:"
labels: [bug]
assignees: "true"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below.

  - type: input
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: Tell us what you saw!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we make this bug happen again?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: false

  - type: input
    id: system-info
    attributes:
      label: System Info
      description: What OS and version are you on?
      placeholder: e.g. macOS 14.2, Windows 11, Ubuntu 22.04
    validations:
      required: false
