name: Playwright Tests
on:
  pull_request:

jobs:
  test:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Run checks
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: .framework/react/frontend

      - name: Install dependencies
        run: yarn install
        working-directory: .framework/react/frontend

      - name: Run frontend client
        run:  WILCO_ID=0 REACT_APP_BACKEND_URL=http://localhost:3001 yarn start >& /dev/null &
        working-directory: .framework/react/frontend

      - name: Install test deps
        run: yarn install
        working-directory: tests/frontend

      - name: Run Playwright tests
        run: yarn test
        working-directory: tests/frontend
