name: E2E Rails

on:
  pull_request:

jobs:
  ci-checks:
    name: Pr checks
    runs-on: ubuntu-20.04
    timeout-minutes: 6

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out project
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          working-directory: .framework/rails/backend
          bundler-cache: true

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - run: bundle install
        working-directory: .framework/rails/backend

      - run: DATABASE_URL=postgresql://postgres:postgres@localhost/anythink-market  bin/rails db:create db:migrate
        working-directory: .framework/rails/backend

      - run: ENGINE_BASE_URL=http://localhost:3003 WILCO_ID=0 DATABASE_URL=postgresql://postgres:postgres@localhost/anythink-market bin/rails s >& /dev/null &
        working-directory: .framework/rails/backend

      - name: Run checks
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: tests/e2e/yarn.lock

      - run: yarn install
        working-directory: tests/e2e/

      - run: yarn wait-on http://localhost:3000/health --timeout 5000
        working-directory: tests/e2e/

      - run: yarn test
        working-directory: tests/e2e/
