name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Run checks
        working-directory: .framework/node/backend
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - run: yarn install
        working-directory: .framework/node/backend
      - run: yarn start-test
        working-directory: .framework/node/backend
      - run: yarn install
        working-directory: .tests/http-tests/
      - run: yarn test
        working-directory: .tests/http-tests/