name: Continuous Integration Node

on:
  pull_request:

jobs:
  ci-checks:
    name: Pr checks
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Run checks
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: .framework/node/backend

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: "4.4"

      - run: yarn install
        working-directory: .framework/node/backend
      - run: yarn start-test >& /dev/null &
        working-directory: .framework/node/backend
      - run: yarn install
        working-directory: tests/http-tests/
      - run: yarn test
        working-directory: tests/http-tests/